<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <StaticWebAssetBasePath>/</StaticWebAssetBasePath>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>UmbHost.Cloudflare.Purge</PackageId>
    <Product>UmbHost.Cloudflare.Purge</Product>
    <Title>UmbHost.Cloudflare.Purge</Title>
    <Authors>UmbHost Limited</Authors>
    <Company>UmbHost Limited</Company>
    <Copyright>(c) $([System.DateTime]::Now.ToString(`yyyy`)) UmbHost Limited</Copyright>
    <Description>Purge the Cloudflare CDN from the Tree, Dashboard and on Publish, Unpublish and Delete of Content and Media items</Description>
    <PackageProjectUrl>https://umbhost.net</PackageProjectUrl>
    <RepositoryUrl>https://github.com/UmbHost/UmbHost.Cloudflare.Purge</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <PackageTags>umbraco-marketplace;umbraco;cloudflare;cache;purge</PackageTags>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\icon.png" Pack="true" PackagePath="\" Visible="false" />
    <None Include="..\README.md" Pack="true" PackagePath="\" Visible="false" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="Umbraco.Cms.Web.Website" Version="18.0.2" />
    <PackageReference Include="Umbraco.Cms.Web.Common" Version="18.0.2" />
    <PackageReference Include="Umbraco.Cms.Api.Common" Version="18.0.2" />
    <PackageReference Include="Umbraco.Cms.Api.Management" Version="18.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ClientAssetsInputs Include="Client\**" Exclude="$(DefaultItemExcludes)" />

    <!-- Dont include the client folder as part of packaging nuget build -->
    <Content Remove="Client\**" />

    <!-- However make the Umbraco-package.json included for dotnet pack or nuget package and visible to the solution -->
    <None Include="Client\public\umbraco-package.json" Pack="false" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

</Project>
