// This file is auto-generated by @hey-api/openapi-ts

export type AllSettings = {
    alwaysOnline?: null | AlwaysOnline;
    browserCacheTtl?: null | BrowserCacheTtl;
    cacheLevel?: null | CacheLevel;
    developmentMode?: null | DevelopmentMode;
};

export type AlwaysOnline = {
    id: string;
    value: SettingsValueEnum;
    modified_on?: string | null;
    editable: boolean;
};

export type BrowserCacheTtl = {
    id: string;
    value: BrowserCacheTtlEnum;
    modified_on?: string | null;
    editable: boolean;
};

export type BrowserCacheTtlEnum = number;

export type CacheLevel = {
    id: string;
    value?: null | CacheLevelEnum;
    modified_on?: string | null;
    editable: boolean;
};

export type CacheLevelEnum = 'Aggressive' | 'Basic' | 'Simplified';

export type ConfigurationStatus = {
    isConfigured: boolean;
    isDisabled: boolean;
    hasAuthKey: boolean;
    hasZones: boolean;
    requiresEmail: boolean;
    hasEmail: boolean;
};

export type DevelopmentMode = {
    id: string;
    value: SettingsValueEnum;
    modified_on: string;
    time_remaining: number | string;
    editable: boolean;
};

export type EnumDescription = {
    value: number | string;
    name: string;
};

export type NewAlwaysOnline = {
    value: string;
};

export type NewBrowserCacheTtl = {
    value: number | string;
};

export type NewCacheLevel = {
    value: string;
};

export type NewDevelopmentMode = {
    value: string;
};

export type SettingsValueEnum = 'On' | 'Off' | 'Lossless' | 'Lossy';

export type TreePurge = {
    unique: string;
    culture?: string | null;
};

export type UmbHostCloudflarePurgeZone = {
    domain: string;
    zoneId: string;
};

export type BrowserTtlOptionsResponse = Array<EnumDescription>;

export type GetCacheSettingsData = {
    zoneId?: string;
};

export type GetCacheSettingsResponse = AllSettings;

export type GetZonesResponse = Array<UmbHostCloudflarePurgeZone>;

export type ToggleAlwaysOnlineData = {
    requestBody: NewAlwaysOnline;
    zoneId?: string;
};

export type ToggleAlwaysOnlineResponse = AlwaysOnline;

export type ToggleBrowserCacheTtlData = {
    requestBody: NewBrowserCacheTtl;
    zoneId?: string;
};

export type ToggleBrowserCacheTtlResponse = BrowserCacheTtl;

export type ToggleCachingLevelData = {
    requestBody: NewCacheLevel;
    zoneId?: string;
};

export type ToggleCachingLevelResponse = CacheLevel;

export type ToggleDevelopmentModeData = {
    requestBody: NewDevelopmentMode;
    zoneId?: string;
};

export type ToggleDevelopmentModeResponse = DevelopmentMode;

export type GetConfigurationStatusResponse = ConfigurationStatus;

export type AllResponse = unknown;

export type CustomData = {
    requestBody?: null | Array<(string)>;
};

export type CustomResponse = unknown;

export type MediaFolderData = {
    requestBody?: null | number | string | null;
};

export type MediaFolderResponse = unknown;

export type NodeData = {
    requestBody?: null | TreePurge;
};

export type NodeResponse = unknown;

export type $OpenApiTs = {
    '/umbraco/umbhostcloudflarepurge/v1.0/cache-settings/browserttloptions': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: Array<EnumDescription>;
                /**
                 * The resource is protected and requires an authentication token
                 */
                401: unknown;
            };
        };
    };
    '/umbraco/umbhostcloudflarepurge/v1.0/cache-settings/getcachesettings': {
        get: {
            req: GetCacheSettingsData;
            res: {
                /**
                 * OK
                 */
                200: AllSettings;
                /**
                 * Bad Request
                 */
                400: string;
                /**
                 * The resource is protected and requires an authentication token
                 */
                401: unknown;
            };
        };
    };
    '/umbraco/umbhostcloudflarepurge/v1.0/cache-settings/getzones': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: Array<UmbHostCloudflarePurgeZone>;
                /**
                 * The resource is protected and requires an authentication token
                 */
                401: unknown;
            };
        };
    };
    '/umbraco/umbhostcloudflarepurge/v1.0/cache-settings/togglealwaysonline': {
        patch: {
            req: ToggleAlwaysOnlineData;
            res: {
                /**
                 * OK
                 */
                200: AlwaysOnline;
                /**
                 * Bad Request
                 */
                400: string;
                /**
                 * The resource is protected and requires an authentication token
                 */
                401: unknown;
            };
        };
    };
    '/umbraco/umbhostcloudflarepurge/v1.0/cache-settings/togglebrowsercachettl': {
        patch: {
            req: ToggleBrowserCacheTtlData;
            res: {
                /**
                 * OK
                 */
                200: BrowserCacheTtl;
                /**
                 * Bad Request
                 */
                400: string;
                /**
                 * The resource is protected and requires an authentication token
                 */
                401: unknown;
            };
        };
    };
    '/umbraco/umbhostcloudflarepurge/v1.0/cache-settings/togglecachinglevel': {
        patch: {
            req: ToggleCachingLevelData;
            res: {
                /**
                 * OK
                 */
                200: CacheLevel;
                /**
                 * Bad Request
                 */
                400: string;
                /**
                 * The resource is protected and requires an authentication token
                 */
                401: unknown;
            };
        };
    };
    '/umbraco/umbhostcloudflarepurge/v1.0/cache-settings/toggledevelopmentmode': {
        patch: {
            req: ToggleDevelopmentModeData;
            res: {
                /**
                 * OK
                 */
                200: DevelopmentMode;
                /**
                 * Bad Request
                 */
                400: string;
                /**
                 * The resource is protected and requires an authentication token
                 */
                401: unknown;
            };
        };
    };
    '/umbraco/umbhostcloudflarepurge/v1.0/configuration/status': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: ConfigurationStatus;
                /**
                 * The resource is protected and requires an authentication token
                 */
                401: unknown;
            };
        };
    };
    '/umbraco/umbhostcloudflarepurge/v1.0/purge/all': {
        post: {
            res: {
                /**
                 * Accepted
                 */
                202: unknown;
                /**
                 * Bad Request
                 */
                400: unknown;
                /**
                 * The resource is protected and requires an authentication token
                 */
                401: unknown;
            };
        };
    };
    '/umbraco/umbhostcloudflarepurge/v1.0/purge/custom': {
        post: {
            req: CustomData;
            res: {
                /**
                 * Accepted
                 */
                202: unknown;
                /**
                 * Bad Request
                 */
                400: unknown;
                /**
                 * The resource is protected and requires an authentication token
                 */
                401: unknown;
            };
        };
    };
    '/umbraco/umbhostcloudflarepurge/v1.0/purge/mediafolder': {
        post: {
            req: MediaFolderData;
            res: {
                /**
                 * Accepted
                 */
                202: unknown;
                /**
                 * Bad Request
                 */
                400: unknown;
                /**
                 * The resource is protected and requires an authentication token
                 */
                401: unknown;
            };
        };
    };
    '/umbraco/umbhostcloudflarepurge/v1.0/purge/node': {
        post: {
            req: NodeData;
            res: {
                /**
                 * Accepted
                 */
                202: unknown;
                /**
                 * Bad Request
                 */
                400: unknown;
                /**
                 * The resource is protected and requires an authentication token
                 */
                401: unknown;
            };
        };
    };
};