name: code-scan

on:
  push:
    branches: [ develop* ]
  pull_request:
    branches: [ develop* ]
  schedule:
    - cron: "0 12 * * MON"
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  code-ql:

    runs-on: windows-latest

    permissions:
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ "csharp" ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: "7.0.304"

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}

    - name: Autobuild
      uses: github/codeql-action/autobuild@v2

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:${{ matrix.language }}"
